### ISSUE TITLE
Adicionar node_modules no .gitignore

### ISSUE THREAD

**Issue by gspaiva** [senhordrio/twitter-bot#2]
É uma boa prática não subir os node_modules para o repositório remoto pelo fato de ser uma pasta com grande quantidade de dados, além de ser desnecessário pois as libs já ficam descritas no package.json e com o npm/yarn install as depedências são instaladas na máquina onde a sua aplicação em node.js irá ser executada.

**Comment by senhordrio** [comment]
@gspaiva você tem razão! Obrigado pelo toque.
